Portfolio: finish mobile version
maths29/mobile-workSections pull request #1
Opened 2023-04-27 14:37 UTC by maths29

in this project I:
Added the work sections
Added the About-Me section and i
Added a contact me form

2023-04-27 15:58 UTC, stanleySimeon requested changes
# Hi @maths29 
 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media2.giphy.com/media/vQGBDTkhtIunaJYmRF/giphy-downsized.gif?cid=29caca75sf3uq9y4qgulk5ybbojwg94b4zo6temfzeel417x&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g
)

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

# Required Changes ♻️

* [ ] I noticed that the index.html file wasn't included, and I wanted to kindly suggest that you add it to the pull request. This will help ensure that your changes can be properly reviewed and merged.

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @stanleySimeon in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 15:58 UTC, stanleySimeon commented on README.md
> +
Kindly if you happen to come across a test section in your project that isn't necessary, it might be a good idea to consider removing it.😁

2023-04-27 15:58 UTC, stanleySimeon commented on README.md
> +
I think it would be a great idea to provide a clear and kind explanation of how to clone the project. Not only will this make the project look more professional, but it will also make it easier for others to understand and follow the cloning process. 😁

2023-04-27 15:58 UTC, stanleySimeon commented on README.md
> +
Kindly if you're able to provide these steps, it would be a fantastic way to make your project look more professional. By outlining the process and making it easy to understand, you'll not only elevate the project's quality, but you'll also make it more accessible to others who may want to replicate or work on it.😁

2023-04-27 15:58 UTC, stanleySimeon commented on style.css
> -}
According to the project requirements you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card.
<img width="1036" alt="Screenshot 2023-04-27 at 11 43 05" src="https://user-images.githubusercontent.com/91237525/234915010-74fcb60b-03fe-4ab1-ad01-14ffe1a49105.png">

>According to the Figma template, I just wanted to bring to your attention that there might be a slight inconsistency between your project's design and the Figma template. It's a small detail, but I thought it might be helpful to bring it up so that your project can look as professional as possible. I suggest taking a look at the design to see if there are any areas that need to be adjusted to match the template more closely.

### The Figma design

<img width="416" alt="Screenshot 2023-04-27 at 11 45 36" src="https://user-images.githubusercontent.com/91237525/234915641-950865f5-d1c5-41dc-84e7-6afbb29c1bfe.png">

### Your Design

<img width="320" alt="Screenshot 2023-04-27 at 11 51 58" src="https://user-images.githubusercontent.com/91237525/234917320-9b61a33a-4fad-4b53-8d25-4bcd6e24232d.png">

2023-04-28 11:53 UTC, divinecharlotte requested changes
Hi @maths29     , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
- linters are passing 👍
- Descriptive commit messages 👍 





 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

☠️ next time make sure that all files you worked on are present in your Pr so that it will be easily for the reviewer to specify exactly what needs to be changed and this will help you to easily understand why changes 

- [ ] kindly consider using a header tag `hx` to your let's connect with `.meet` class to meet the below requirement 👇 
> 1. If there are other titles (e.g., "Let's connect") use a header tag `hx`
1. 

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 11:53 UTC, divinecharlotte commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/iwu-john)
- [ ] kindly consider adding a working link to your lindhin account to give a good user experience  to the people visiting your reademe

2023-04-28 11:53 UTC, divinecharlotte commented on README.md
> +  - [Deployment](#triangular_flag_on_post-deployment)
- [ ] kindly consider adding this section too as this project will be deployed soon you may give it a caption saying `coming soon ` to make it professional

2023-04-28 11:53 UTC, divinecharlotte commented on style.css
>  .structure {
- [ ] Kindly consider giving the whole section container (which has a main class in your case )a grid display  to make   it easier to design this section

2023-04-28 11:53 UTC, divinecharlotte commented on style.css
> +  display: grid;
- [ ] Previously you did it right but when you edited it ruined it kindly consider giving every structure flex display to meet the below 👇 requirement
> For each project
> * The content of the project is aligned with the flexbox

- [ ] and also consider giving this section the same margins (top, bottom, left, right) as defined in the design to make your project an exact duplicate of the one given in Figma. check the image below 👇  to easily see the difference 
- your design 👇 
<img width="364" alt="Screen Shot 2023-04-28 at 13 39 58" src="https://user-images.githubusercontent.com/60146030/235138787-f39d6746-86d8-48b3-b1a3-2d9ac2374fc8.png">


- Figma design 👇 
<img width="383" alt="Screen Shot 2023-04-28 at 13 41 59" src="https://user-images.githubusercontent.com/60146030/235138913-dbc7ab49-9247-44ef-b9d1-949e0e07ae1d.png">

2023-04-28 11:53 UTC, divinecharlotte commented on style.css
>  .structure2 {
- [ ] kindly consider giving all projects the same class in your HTML   and use it to style them at the same time to avoid repeating yourself doing that will make your code DRY (not having stucture1,sctructure2,..... with the same style)

2023-04-29 13:53 UTC, vickymarz approved these changes
Hi @maths29, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Requested change implemented✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions 

- I noticed that the headline and the toolbar section are missing in your webpage which is the first milestone. Please note that your project was divided into milestones so that you can gradually complete your website within a timeframe. So you are not expected to create a separate webpage for the different milestones of your portfolio project. So kidly add the headline and toolbar section back so that your webpage can be whole 👍🏽 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 14:15 UTC, merged