mobile-workSections
maths29/mobile-workSections pull request #2
Opened 2023-05-02 16:13 UTC by maths29

in this project I:
update the contact form in index.html
update the style.css and 
I added the formspree link to the form

2023-05-02 17:27 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @maths29 and @Fombi-Favour👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You used GitHub Flow correctly 👍🏽
✅ Linter checks passed✔️
✅ Used Flexbox to lay out the elements on the page 👍🏽 
✅ Collect data by using the Formspree service✔️


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 17:27 UTC, Johnadibe commented on index.html
> +          </form>
> - [ ] Great job to you both👍 Please kindly ensure that the `input` font size stick to the design templates in Figma as much as possible and also the decorator background image close to the "Get in touch" `button`.😊
> 
> Figma design👇:
> 
> ![contact-figma](https://user-images.githubusercontent.com/40009354/235736900-783a2100-f2ce-4871-8207-eb7f4f006b5c.PNG)
> 
> Your design👇:
> 
> ![contact-team](https://user-images.githubusercontent.com/40009354/235736850-2123b4e2-f7aa-4806-a06e-9952d898d5cc.PNG)
>

2023-05-02 17:27 UTC, Johnadibe commented on index.html
> +            <button type="submit" class="submit">Get in touch</button>
> - [ ] Please kindly implement the hover interaction of the button state by adding its `box-shadow` to match the Figma design👍
> 
> Figma design👇:
> 
> ![btn-hover](https://user-images.githubusercontent.com/40009354/235739695-c377564d-b7f3-44ee-8b34-660469a70616.PNG)
> 
> Your design👇:
> 
> ![btn](https://user-images.githubusercontent.com/40009354/235739776-1ec3b8dc-1492-482c-ba0f-b1f25748a34e.PNG)
> 
> 
>

2023-05-03 08:50 UTC, usorfaitheloho requested changes
> Hi @maths29  ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> ## Highlights
> * All linter checks passed ✔️
> * Descriptive pull request ✔️
> * Implemented the hover button interaction ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 08:50 UTC, usorfaitheloho commented on index.html
> +            <button type="submit" class="submit">Get in touch</button>
Please I'd suggest your design follows the Figma template as closely as possible, the `placeholder` text is different from the one we have in the design, kindly re-adjust it to the placeholder text present in the design given so as to have a better design 😄

2023-05-03 08:50 UTC, usorfaitheloho commented on style.css
> +  background-size: contain;
Please as suggested by the previous reviewer, kindly adjust the image on the background of the form to be in a position similar to what we have in the design given. yours is at the end of the page but what is in the design is close to the `texxtarea` 👍 

figma design :

![image](https://user-images.githubusercontent.com/20537712/235870567-33f72256-317a-4d44-905d-045e7915b70f.png)

Your design :

![image](https://user-images.githubusercontent.com/20537712/235870698-1a96d014-b323-4191-9880-8e6a27af7d99.png)

2023-05-03 10:28 UTC, tugsem commented
## STATUS: APPROVED 👍🎯  
Hello @maths29 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⭐ 
✔️ correct use of github flow
✔️ linters are passing
✔️ professional documentation
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 13:06 UTC, merged