desktop view
maths29/mobile-workSections pull request #3
Opened 2023-05-05 17:06 UTC by maths29

In this project I:
- Added a desktop version to the project
- Added modifications to style.css

2023-05-05 20:10 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @maths29 , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Indeed you did an exceptional but still, there is room for changes to complete this project. 💯


## Highlights
💹 Well-implemented design. 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

Please consider always using the name of your feature branch as a way to highlight what you did in it (e.g. 'created_sidebar' or 'added_comments_section')  In this case, your branch name is `feature-b` which is not professional.

>You can name it `feature-1/portfolio-desktop-version` or something else that describes what you did in the branch.

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 20:10 UTC, ABDULALI3468 commented on style.css
> +  }
Please consider making the design exactly inaccordanc with the Figma template currently the positions of elements in both of the designs are very different. 

> Remember don't you can target different desktop screens like in ranges as currently if I see your design at 800px it is broken at many places as you added long margins to individual elements so consider focusing on that also.

### VIDEO DEMONSTRATION:-

https://user-images.githubusercontent.com/94223367/236555543-0813f84b-5b68-4663-ad89-70d9837c5c10.mp4

### FIGMA DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/236555689-ef967229-5191-4904-8cfb-2568c639eee1.png)

2023-05-05 20:10 UTC, ABDULALI3468 commented on style.css
> +  }
Please consider using the same letter spacing as used in the Figma design to match the design and to meet the project requirements.

### REMEMBER:-

THE GOAL OF THE PROJECT TO MAKE A LOOK ALIKE DESIGN OF THE TEMPLATE!

2023-05-05 20:10 UTC, ABDULALI3468 commented on style.css
> +  }
Please consider making the design exactly inaccordanc with the Figma template currently the positions of elements in both of the designs are very different. 

> Remember don't you can target different desktop screens like in ranges as currently if I see your design at 800px it is broken at many places as you added long margins to individual elements so consider focusing on that also.

### VIDEO DEMONSTRATION:-



https://user-images.githubusercontent.com/94223367/236557164-283ba3f6-d5c3-47a6-b8d8-2354716e6476.mp4


### FIGMA DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/236557248-03c2af72-f22f-4c3e-9b63-770956463251.png)

2023-05-05 20:10 UTC, ABDULALI3468 commented on style.css
> +  }
The background images are not showing in the design please consider making the design in accordance with the template to meet the project requirements ✅ 

![image](https://user-images.githubusercontent.com/94223367/236557780-f5d7d899-531e-4810-a0b8-e35fad96c350.png)

2023-05-05 20:10 UTC, ABDULALI3468 commented on style.css
>  }
Remember the mobile version still needs to look perfect as it was before currently there is a different in position with respect to design please rectify it to meet the design guidelines.

![image](https://user-images.githubusercontent.com/94223367/236558225-f54e65f4-e5a4-423b-b976-3ec5ded4946e.png)

2023-05-05 20:10 UTC, ABDULALI3468 commented on index.html
>        </nav>
Please consider positioning the logo of the navbar similar to the design to meet the project requirements.

### YOUR DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/236558943-31026080-0d7b-45c5-9cbd-98b761311b19.png)

### FIGMA DESIGN:-

![image](https://user-images.githubusercontent.com/94223367/236558997-bb1eb03f-954f-466e-9a4f-a58166700dbf.png)

2023-05-06 13:53 UTC, OyePriscilla requested changes
Hi @maths29 👏 👏 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
App responsiveness ✔️ 
Uses both Flexbox and Grid in order to layout the elements on the page ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 13:53 UTC, OyePriscilla commented on index.html
> +              hesitate to contact me.
- [ ] As suggested earlier, kindly work more on the about me section in accordance to the given template. 👇 
## Your Design
<img width="818" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/236628178-ac97958b-8373-4099-b0e1-df3c7b37c954.png">

2023-05-06 13:53 UTC, OyePriscilla commented on style.css
>  }
- [ ] Please kindly ensure that the mobile version still look as expected as raised earlier. 🙏 
## Your Design
<img width="287" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/236628323-59089b28-7b96-466e-9245-6ae7d67936a5.png">

2023-05-06 13:53 UTC, OyePriscilla requested changes
Hi @maths29 👏 👏 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
App responsiveness ✔️ 
Uses both Flexbox and Grid in order to layout the elements on the page ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 17:42 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @maths29, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


## Optional suggestions

There is still room for improvement but you put enough effort into this project. It is approved and if you want to make it better here is what you can do:    

- [OPTIONAL] Please consider aligning the About section title with the paragraph, I see that you use a lot of fixed margins across your entire stylesheet which makes getting this done a hard task, my suggestion is that you avoid using them unless they are necessary. 🤓 🔧 

![Screenshot from 2023-05-06 12-39-28](https://user-images.githubusercontent.com/77069011/236639031-53005801-ae0f-4be4-927b-4fad90a2bfe2.png)




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 17:50 UTC, merged