Popup version project
maths29/mobile-workSections pull request #9
Opened 2023-05-19 20:23 UTC by maths29

in this project we:
- implemented the popup version of the project to the 
- index.html and style.css, we also updated the js file using DOM to manipulate the UI interactions 
- we also added another js file for populating the content of the project section dynamically

2023-05-19 23:34 UTC, OyePriscilla requested changes
Hi @maths29 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Professional README file ✔️ 
Implemented pop-up modal ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 23:34 UTC, OyePriscilla commented on display_portfolio.js
> +// console.log(projectsData);
- [ ] KIndly remove this commented code, this will make your codebase to be clean. ℹ️

2023-05-19 23:34 UTC, OyePriscilla commented on display_portfolio.js
> +          </div>
- [ ] Kindly add `alt` attribute to the cards images, the required alt attribute specifies an alternate text for an image, if the image cannot be displayed. ℹ️

2023-05-19 23:34 UTC, OyePriscilla commented on display_portfolio.js
> +});
- [ ] For your app to be according to the given design, kindly work more on the following: 

1. The `margins` around the pop-up.
2. The `spacing` between the two buttons.
3. The `hr` element is not bold as we have it the template.
4. Lastly, the stacks margin-bottom (`canopy, Back End Dev ...`)

## Figma Design
<img width="437" alt="Untitled" src="https://github.com/maths29/mobile-workSections/assets/103386183/686903c6-a750-463b-ad4e-25725fa399d7">

## Your Design
<img width="936" alt="Untitled" src="https://github.com/maths29/mobile-workSections/assets/103386183/5845f8b4-9873-448e-9159-1c5b0adfd5ac">

2023-05-20 02:53 UTC, Strangeal approved these changes
Hi @maths29, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 03:05 UTC, merged